# Generated by Django 4.2.4 on 2024-06-02 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OJTCompany',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='', max_length=225)),
                ('owner', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('company_contact', models.CharField(max_length=50, null=True)),
                ('number_of_slots', models.PositiveIntegerField(default=1)),
                ('shift', models.CharField(choices=[('Day Shift', 'Day Shift'), ('Night Shift', 'Night Shift')], default='Day Shift', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('seminar_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('theme', models.CharField(default='', max_length=150)),
                ('date_of_event', models.DateField(default='')),
                ('image', models.FileField(blank=True, null=True, upload_to='upload/seminar_imgs')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.CharField(default='1', max_length=30)),
                ('action', models.CharField(default='None', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('Student', 'Student'), ('Admin', 'Admin')], default='Student', max_length=50)),
                ('content_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Transaction Report',
                'verbose_name_plural': 'Transaction Reports',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('studID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('lrn', models.PositiveBigIntegerField()),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('yearlvl', models.PositiveIntegerField(default=1)),
                ('sex', models.CharField(default='M', max_length=1)),
                ('contact', models.CharField(max_length=50, null=True)),
                ('program', models.CharField(choices=[('Bachelor of Science Information and Technology', 'Bachelor of Science Information and Technology'), ('Bachelor of Elementary Education', 'Bachelor of Elementary Education'), ('Bachelor of Secondary Education', 'Bachelor of Secondary Education'), ('Bachelor of Industrial Technology Major in Computech', 'Bachelor of Industrial Technology Major in Computech'), ('Bachelor of Industrial Engineering', 'Bachelor of Industrial Engineering'), ('Bachelor of Science and Forestry', 'Bachelor of Science and Forestry'), ('Bachelor of Science', 'Bachelor of Science'), ('Bachelor of English Literature', 'Bachelor of English Literature'), ('Bachelor of Science Criminology', 'Bachelor of Science Criminology'), ('Bachelor of Science Hospitality and Management', 'Bachelor of Science Hospitality and Management'), ('Bachelor of Science Hospitality and Tourism', 'Bachelor of Science Hospitality and Tourism'), ('Bachelor of Crafts Arts and Science', 'Bachelor of Crafts Arts and Science'), ('Bachelor of Environmental Science', 'Bachelor of Environmental Science')], default='Bachelor of Science Information and Technology', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, related_name='student_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='student_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='SeminarAttendance',
            fields=[
                ('sem_at_id', models.AutoField(primary_key=True, serialize=False)),
                ('attended', models.BooleanField(default=False)),
                ('ispending', models.BooleanField(default=False)),
                ('seminar_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobplacement.seminar')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobplacement.studentuser')),
            ],
        ),
        migrations.CreateModel(
            name='OJTStudent',
            fields=[
                ('ojt_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_started', models.DateField(auto_now=True)),
                ('duration', models.PositiveIntegerField(default=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobplacement.ojtcompany')),
                ('studID', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='jobplacement.studentuser')),
            ],
            options={
                'ordering': ['date_started'],
            },
        ),
        migrations.CreateModel(
            name='OJTRequirements',
            fields=[
                ('ojt_requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('non_disclosure', models.FileField(blank=True, upload_to='')),
                ('biodata', models.FileField(blank=True, upload_to='')),
                ('parents_consent', models.FileField(blank=True, upload_to='')),
                ('application_letter', models.FileField(blank=True, upload_to='')),
                ('medical', models.FileField(blank=True, upload_to='')),
                ('moa', models.FileField(blank=True, upload_to='')),
                ('endorsement', models.FileField(blank=True, upload_to='')),
                ('certification', models.FileField(blank=True, upload_to='')),
                ('nondis_stat', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('No file', 'No file')], default='No file', max_length=20)),
                ('biodata_stat', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('No file', 'No file')], default='No file', max_length=20)),
                ('consent_stat', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('No file', 'No file')], default='No file', max_length=20)),
                ('apl_letter_stat', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('No file', 'No file')], default='No file', max_length=20)),
                ('medical_stat', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('No file', 'No file')], default='No file', max_length=20)),
                ('moa_stat', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('No file', 'No file')], default='No file', max_length=20)),
                ('endorsement_stat', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('No file', 'No file')], default='No file', max_length=20)),
                ('cert_stat', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('No file', 'No file')], default='No file', max_length=20)),
                ('is_valid', models.BooleanField(default=True)),
                ('company_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobplacement.ojtcompany')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobplacement.studentuser')),
            ],
        ),
        migrations.CreateModel(
            name='JobPlacementAdminUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('admin_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('middlename', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, related_name='admin_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='admin_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
