# Generated by Django 4.2.4 on 2024-06-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobplacement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobplacementadminuser',
            name='admin_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
